"""first

Revision ID: 8fc56129d7fb
Revises: 
Create Date: 2026-08-12 07:06:30.245269+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fc56129d7fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('root','admin','user')", name='users_role_check'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_users_username'), 'users', ['username'], unique=True, schema='ai')
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['ai.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_auth_sessions_token'), 'auth_sessions', ['token'], unique=True, schema='ai')
    op.create_index(op.f('ix_ai_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False, schema='ai')
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['ai.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_chat_sessions_owner_id'), 'chat_sessions', ['owner_id'], unique=False, schema='ai')
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['ai.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='ai'
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_content', sa.Text(), nullable=False),
    sa.Column('assistant_content', sa.Text(), nullable=True),
    sa.Column('user_tokens_in', sa.Integer(), nullable=False),
    sa.Column('assistant_tokens_out', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai.chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('idx_chat_messages_session', 'chat_messages', ['session_id', 'created_at'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_session', table_name='chat_messages', schema='ai')
    op.drop_table('chat_messages', schema='ai')
    op.drop_table('user_preferences', schema='ai')
    op.drop_index(op.f('ix_ai_chat_sessions_owner_id'), table_name='chat_sessions', schema='ai')
    op.drop_table('chat_sessions', schema='ai')
    op.drop_index(op.f('ix_ai_auth_sessions_user_id'), table_name='auth_sessions', schema='ai')
    op.drop_index(op.f('ix_ai_auth_sessions_token'), table_name='auth_sessions', schema='ai')
    op.drop_table('auth_sessions', schema='ai')
    op.drop_index(op.f('ix_ai_users_username'), table_name='users', schema='ai')
    op.drop_table('users', schema='ai')
    # ### end Alembic commands ###